name: Tag Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5' # Run every Friday at midnight UTC

permissions:
  contents: write
  packages: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.version.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Trust Mise
        run: mise trust

      - name: Install Dependencies
        run: mise run init

      - name: Version and Tag
        id: version
        run: mise run version:bump

  trigger-production:
    needs: [tag-release]
    if: needs.tag-release.outputs.tag_name != ''
    uses: ./.github/workflows/ci-main.yml
    with:
      tag_name: ${{ needs.tag-release.outputs.tag_name }}
